### PR TITLE
Added change I2C address feature

### PR DESCRIPTION
**Pull request by kgrech**
Hello @ladyada 

I am submitting a PR to be able to change I2C address of the sensor device. It provides same functionality as https://github.com/adafruit/Adafruit_VL6180X/pull/4, however it does not have merge conflict with current library codebase.

I have added the following into my commit:
- changeAddress function to change sensor address
- getAddress method to get current address of the sensor
- Vl6180_changeAddress example to demo how to change sensor address to the address provided by Serial interface
- vl6180_multiple example to prove that once the address is changed multiple devices could work on the same i2c bus
-  increased version in library.properties (not sure if it was needed, let me know if you'd like me to revert this change).

I have tested the changes on my 3 VL sensors and it works fine for me.

Let me know if any changes are suggested.

Thanks, K.

### CODE REVIEW

**Comment by JuliusSustarevas** [comment]
Are there plans to merge this?

**Comment by ladyada** [comment]
@JuliusSustarevas it cant be merged as is because there are conflicts. would you like to try fixin' them or re-submitting the PR?

**Comment by kgrech** [comment]
@ladyada 

I've opened this PR more than 2 years ago and the moment I've opened it had no conflicts, however, I did not see any intent in merging it up until now...

I can fix them conflicts myself, would you be really interested in merging it if I do?

**Comment by ladyada** [comment]
hihi yes we can, please re-submit so it passes CI!

**Comment by kgrech** [comment]
@ladyada I've checked it and I think the same feature is already implemented during these 2 years. I think it was contributed by this PR https://github.com/adafruit/Adafruit_VL6180X/pull/17

I do not think there is anything left to implement. Could you please confirm the same? If so, feel free to close this PR.

**Comment by ladyada** [comment]
oh yeah! ok well thats great :)

**Pull request closed without merging**
