### PR TITLE
Add continuous range support also updated example sketch

### PR DESCRIPTION
**Pull request by KurtE**
Not sure if I took this far enough, as I only added continuous support for ranging, not the LUX reads, which also could be made to either or both...

But I also revamped the triple sketch, which has quick and dirty one character mode settings to have one mode for doing continuous.

Also in this version of the sketch is a timed version using GPIO pins for testing completion versus the polling method.  So far I only tested the GPIO way with the continuous mode, but added support for the polling way as well.

Probably getting much done with this round of playing around, especially since I am not sure if I will actully use these sensors, but has been fun.

So far all of my testing has been done with Teensy 4.1 board.

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
thanks we can merge once it passes CI :)

**Comment by KurtE** [comment]
Thanks, it took me a few passes to figure out what all clang/doxygen want...  
The last was needing to add some form of comment on #define in the cpp file.  I put one in in the format of similar ones
in the .h file.  And finally its happy.

Probably should find the set of tools to run it before PR instead of fixing up as it runs through the checks

**Comment by ladyada** [comment]
yeah we recommend installing clang - its pretty easy to install on any platform and comes with `clang-format` - we use the default setup for clang-format so no special init files needed :)

**Comment by ladyada** [comment]
(also clang-format -i will make the changes for you so you dont have to fix them yourself)

**Pull request merged**
