### PR TITLE
Add async interaction model

### PR DESCRIPTION
**Pull request by kvc0**
* asyncReadRange
    Queue up a range read to be completed at some future point.
* asyncReadLux
    Queue up a lux read to be completed at some future point.
* asyncLoop
    Anchor the future point to a method call from loop()

The async model herein still relies on polling, but it does so while
surrendering execution back to the loop thread.  The developer is free
to provide any loop-compatible callback (i.e., no system interrupt
context limitations), though it's obvious to either flip a flag like
"ready" or add a schedule loop wherein the completion functions end up
scheduling another async read (this is what I do).

Without the async interaction, a lux reading blocks for ~100ms, and a
range reading blocks for ~50ms.  With async model, the interactions with
the library are typically sub-millisecond.

example 50fps demo

### CODE REVIEW

**Comment by kvc0** [comment]
I'm not going to invest the time to fix this build for compilers which define `__cplusplus >= 201103L` _and_ which do not have `<functional>`.  I could rework the feature to remove functional behavior, but that's lower on my list of priorities.  Works great for Particle devices :-)

**Comment by ladyada** [comment]
could you pass in a normal C callback?

**Comment by kvc0** [comment]
For sure, it could could be made to work!  It'd take me a few hours to strip `functional` though - I may circle back around but not right now.  It's working super for my current project, and I'll happily merge upstream updates in the future.  Might be worth considering adding a `c++` branch to some of these libraries?  11's been out for a while at this point, and it makes certain design patterns much simpler to implement.  Whatever the case, thanks for this lib - it would have taken me days to get this far without it!

**Comment by ladyada** [comment]
we want to only have one branch of development, so maintenence isn't hard. please submit any fixes so that they will continue to work with all arduino IDE compilers (as it is now!)

**Pull request closed without merging**
